# Starter pipeline

trigger:
- master


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'custom'
    customCommand: 'build'
    workingDirectory: '.'
- task: Go@0
  inputs:
    command: 'test'
- task: Go@0
  inputs:
    workingDirectory: '.'
    command: 'custom'
    customCommand: 'run'
    arguments: 'main.go'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'